<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Capture.Core\Capture.Core.csproj" />
    <ProjectReference Include="..\Capture.Therefore\Capture.Therefore.csproj" />
  </ItemGroup>
</Project>
